/**
 * Spotlight — `init` command
 *
 * Scaffolds a complete Spotlight project directory with a sensible
 * default config, an assets folder, and an optional TypeScript schema.
 */

import {
  mkdirSync,
  writeFileSync,
  existsSync,
  readdirSync,
} from 'node:fs';
import { resolve, join } from 'node:path';
import inquirer from 'inquirer';
import ora from 'ora';
import boxen from 'boxen';
import chalk from 'chalk';
import { brand } from '../index.js';
import { TEMPLATES, THEMES } from '../data/catalog.js';
import { type SpotlightConfig } from './create.js';

// ─── Types ────────────────────────────────────────────────────────────────────

interface InitOptions {
  template?: string;
  ts: boolean;
}

// ─── Default config factory ───────────────────────────────────────────────────

function buildDefaultConfig(projectName: string, templateId: string): SpotlightConfig {
  return {
    version: '1',
    meta: {
      createdAt: new Date().toISOString(),
      cliVersion: '0.1.0',
    },
    project: {
      name: projectName,
      tagline: 'The fastest way to ship.',
      description: 'Add your product description here.',
      url: 'https://example.com',
    },
    video: {
      template: templateId,
      theme: 'midnight',
      aspectRatio: '16:9',
      duration: 30,
      fps: 30,
      quality: 'standard',
    },
    assets: {
      logo: 'assets/logo.png',
      screenshots: [
        'assets/screenshot-1.png',
        'assets/screenshot-2.png',
        'assets/screenshot-3.png',
      ],
      music: 'assets/background.mp3',
    },
    export: {
      format: 'mp4',
      outputPath: `${projectName.toLowerCase().replace(/\s+/g, '-')}-launch.mp4`,
    },
  };
}

// ─── TypeScript schema ────────────────────────────────────────────────────────

const TS_SCHEMA = `/**
 * Spotlight config schema — auto-generated by \`spotlight init\`
 * You can use this to get type-safety when editing your config via ts-node
 * or with a JSON schema validator that supports TypeScript types.
 */

export interface SpotlightConfig {
  version: '1';
  meta: {
    createdAt: string;
    cliVersion: string;
  };
  project: {
    name: string;
    tagline: string;
    description?: string;
    url?: string;
  };
  video: {
    /** Template ID — run \`spotlight templates\` for all options */
    template: string;
    /** Theme ID — midnight | aurora | ember | frost | noir | sunset */
    theme: string;
    /** Aspect ratio — e.g. "16:9", "9:16", "1:1" */
    aspectRatio: string;
    /** Duration in seconds */
    duration: number;
    /** Frames per second */
    fps: 24 | 30 | 60;
    quality: 'draft' | 'standard' | 'ultra';
  };
  assets: {
    logo?: string;
    screenshots: string[];
    music?: string;
  };
  export: {
    format: 'mp4' | 'webm' | 'gif';
    outputPath: string;
  };
}
`;

// ─── .gitignore template ──────────────────────────────────────────────────────

const GITIGNORE = `# Spotlight output
*.mp4
*.webm
*.gif

# Node
node_modules/

# OS
.DS_Store
Thumbs.db
`;

// ─── README template ──────────────────────────────────────────────────────────

function buildReadme(projectName: string): string {
  return `# ${projectName} — Spotlight Project

Generated with [Spotlight](https://spotlight.dev).

## Getting started

1. Drop your screenshots into the \`assets/\` folder
2. Edit \`spotlight.config.json\` to customise the video
3. Run:

\`\`\`bash
spotlight render
\`\`\`

## Available commands

| Command                      | Description                          |
|------------------------------|--------------------------------------|
| \`spotlight render\`           | Render to video                      |
| \`spotlight render --quality ultra\` | Maximum quality render         |
| \`spotlight templates\`        | Browse all templates                 |
| \`spotlight create\`           | Re-run the interactive wizard        |

## Config reference

See \`spotlight.config.json\`. All fields are documented inline.

> Tip: run \`spotlight init --ts\` to generate a TypeScript schema for full type-safety.
`;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function isDirectoryEmpty(dir: string): boolean {
  try {
    return readdirSync(dir).length === 0;
  } catch {
    return true;
  }
}

async function confirmOverwrite(dir: string): Promise<boolean> {
  const { proceed } = await inquirer.prompt<{ proceed: boolean }>([
    {
      type: 'confirm',
      name: 'proceed',
      message:
        brand.warning(`Directory ${brand.white(dir)} is not empty. Continue anyway?`),
      default: false,
    },
  ]);
  return proceed;
}

// ─── Entry point ──────────────────────────────────────────────────────────────

export async function initCommand(directory: string, options: InitOptions): Promise<void> {
  const targetDir = resolve(directory);
  const dirExists = existsSync(targetDir);

  // Confirm if directory is non-empty
  if (dirExists && !isDirectoryEmpty(targetDir)) {
    const ok = await confirmOverwrite(targetDir);
    if (!ok) {
      console.log(brand.dim('\n  Aborted.\n'));
      return;
    }
  }

  // ── Pick template ──────────────────────────────────────────────────────────
  let templateId = options.template;

  if (!templateId) {
    const { chosen } = await inquirer.prompt<{ chosen: string }>([
      {
        type: 'list',
        name: 'chosen',
        message: brand.primary('Which template should we scaffold from?'),
        choices: TEMPLATES.map((t) => ({
          name: `${brand.accent(t.id.padEnd(28))} ${brand.dim(t.description)}`,
          value: t.id,
        })),
        pageSize: 12,
      },
    ]);
    templateId = chosen;
  }

  if (!TEMPLATES.find((t) => t.id === templateId)) {
    console.error(brand.error(`Unknown template: ${brand.bold(String(templateId))}`));
    console.error(brand.dim(`Run ${brand.white('spotlight templates')} to see all options.`));
    process.exit(1);
  }

  // After the guard above, templateId is guaranteed to be a non-empty string.
  const resolvedTemplateId = templateId as string;

  // ── Pick project name ──────────────────────────────────────────────────────
  const defaultName = directory === '.' ? 'my-launch' : directory.split('/').pop() ?? 'my-launch';

  const { projectName } = await inquirer.prompt<{ projectName: string }>([
    {
      type: 'input',
      name: 'projectName',
      message: brand.primary('Project name:'),
      default: defaultName,
      filter: (v: string) => v.trim(),
      validate: (v: string) => (v.length > 0 ? true : 'Project name cannot be empty'),
    },
  ]);

  // ── Scaffold ───────────────────────────────────────────────────────────────
  const spinner = ora({ text: brand.dim('Scaffolding project…'), color: 'magenta' }).start();

  // Directories
  const assetsDirs = [
    join(targetDir, 'assets'),
  ];

  const filesToWrite: Array<{ path: string; content: string }> = [
    {
      path: join(targetDir, 'spotlight.config.json'),
      content: JSON.stringify(buildDefaultConfig(projectName, resolvedTemplateId), null, 2) + '\n',
    },
    {
      path: join(targetDir, '.gitignore'),
      content: GITIGNORE,
    },
    {
      path: join(targetDir, 'README.md'),
      content: buildReadme(projectName),
    },
  ];

  if (options.ts) {
    filesToWrite.push({
      path: join(targetDir, 'spotlight.config.d.ts'),
      content: TS_SCHEMA,
    });
  }

  // Placeholder asset files so the structure is clear
  const placeholderAssets: Array<{ path: string; content: string }> = [
    {
      path: join(targetDir, 'assets', '.gitkeep'),
      content: '',
    },
  ];

  try {
    // Create directories
    mkdirSync(targetDir, { recursive: true });
    for (const dir of assetsDirs) {
      mkdirSync(dir, { recursive: true });
      spinner.text = brand.dim(`Creating ${dir.replace(targetDir, '.')}…`);
      await sleep(80);
    }

    // Write files
    for (const { path, content } of [...filesToWrite, ...placeholderAssets]) {
      writeFileSync(path, content, 'utf8');
      spinner.text = brand.dim(`Writing ${path.replace(targetDir + '/', '')}…`);
      await sleep(80);
    }

    spinner.succeed(brand.success('Project scaffolded successfully'));
  } catch (err) {
    spinner.fail(brand.error('Failed to scaffold project'));
    throw err;
  }

  // ── Summary ────────────────────────────────────────────────────────────────
  const selectedTemplate = TEMPLATES.find((t) => t.id === resolvedTemplateId)!;
  const selectedTheme = THEMES.find((t) => t.id === 'midnight')!;

  const fileTree = [
    brand.dim(`  ${directory}/`),
    brand.dim('  ├── ') + brand.white('spotlight.config.json'),
    brand.dim('  ├── ') + brand.white('README.md'),
    brand.dim('  ├── ') + brand.white('.gitignore'),
    options.ts ? brand.dim('  ├── ') + brand.white('spotlight.config.d.ts') : '',
    brand.dim('  └── ') + brand.white('assets/'),
    brand.dim('       └── ') + brand.dim('.gitkeep'),
  ].filter(Boolean).join('\n');

  console.log(
    boxen(
      [
        brand.primary(brand.bold('Project initialised!')),
        '',
        fileTree,
        '',
        `  ${brand.dim('Template  ')} ${brand.white(selectedTemplate.name)}`,
        `  ${brand.dim('Theme     ')} ${chalk.hex(selectedTheme.primaryColor)(selectedTheme.name)}`,
        `  ${brand.dim('Directory ')} ${brand.white(targetDir)}`,
        '',
        brand.primary(brand.bold('Next steps:')),
        '',
        `  ${brand.accent('1.')} ${brand.white(`cd ${directory}`)}`,
        `  ${brand.accent('2.')} Add your product screenshots to ${brand.white('assets/')}`,
        `  ${brand.accent('3.')} Edit ${brand.white('spotlight.config.json')} to customise`,
        `  ${brand.accent('4.')} ${brand.white('spotlight render')}`,
        '',
        brand.dim(`Full docs at ${brand.white('https://spotlight.dev/docs')}`),
      ].join('\n'),
      {
        padding: 1,
        margin: { top: 1, bottom: 1, left: 2, right: 2 },
        borderStyle: 'round',
        borderColor: '#A855F7',
        title: brand.secondary(' ready '),
        titleAlignment: 'center',
      },
    ),
  );
}

function sleep(ms: number): Promise<void> {
  return new Promise((res) => setTimeout(res, ms));
}
